name: Publish Package to Github Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.x
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Generate .npmrc for GitHub Packages
        run: |
          echo "@drasla:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_PUBLISH_KEY }}

      - name: Check pnpm version
        run: pnpm --version

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish to Github Packages
        run: pnpm publish --no-git-checks --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{secrets.PACKAGE_PUBLISH_KEY}}

      - name: Remove .npmrc to reset registry for npmjs
        run: rm -f .npmrc

      - name: Publish to NPM.JS
        run: pnpm publish --no-git-checks --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
